version: '3'
services:
  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: "usuarios.controlinmobiliario.cl"
      LETSENCRYPT_HOST: "usuarios.controlinmobiliario.cl"
      LETSENCRYPT_EMAIL: "cristopher@wetrust.cl"
    networks:
      - wetrust
      - sharednet
